pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: ''
            }
        }

        stage('Clean') {
            steps {
                dir('BankingAutomationFramework') {
                    bat 'mvn clean'
                }
            }
        }

        stage('Compile') {
            steps {
                dir('BankingAutomationFramework') {
                    bat 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('BankingAutomationFramework') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('BankingAutomationFramework') {
                    bat 'mvn package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('BankingAutomationFramework') {
                    bat 'docker build -t testng-framework .'
                }
            }
        }

        stage('Docker Run') {
            steps {
                dir('BankingAutomationFramework') {
                    bat 'docker run --rm testng-framework'
                }
            }
        }
    }

    post {
        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }

        always {
            echo 'Pipeline Finished'
        }
    }
}